/**
 * Voice engine for Bedaya.
 *
 * The voice IS the interface — a learner who can't read depends entirely on
 * hearing. So this layer:
 *   - picks the best available Egyptian/Arabic voice and slows it down
 *   - waits for the browser to finish loading voices (Chrome loads async)
 *   - unlocks audio on the first user gesture (browsers block autoplay)
 *   - speaks by KEY first, falling back to TTS — so real recorded clips
 *     (the Umm Yasmin / Amm Hassan cast) can drop in later with no caller
 *     changes: just add files to RECORDINGS.
 */

const GUIDE_GENDER = {
  umm_yasmin: 'female',
  amm_hassan: 'male',
};

// Browsers commonly ship a single Arabic voice (macOS: Maged), so pickVoice
// returns the same voice for both guides. We shape pitch + rate per guide so
// they remain perceptibly distinct even when the underlying voice is identical.
const GUIDE_SHAPE = {
  umm_yasmin: { pitch: 1.35, rate: 0.74 }, // higher, slightly faster — warmer female register
  amm_hassan: { pitch: 0.78, rate: 0.66 }, // lower, slightly slower — older male register
};

// Pre-baked Edge TTS recordings (ar-EG-SalmaNeural / ar-EG-ShakirNeural)
// generated by scripts/generate-voice-clips.mjs. Real Egyptian Arabic voices
// beat the browser-bundled Maged for both quality and dialectal accuracy.
// Each key resolves to per-guide URLs; missing entries fall through to TTS.
const STATIC_PHRASE_KEYS = [
  'welcome', 'pick_guide', 'say_name',
  'home_lesson', 'home_done',
  'phase_warmup', 'phase_trace',
  'phase_story_words', 'phase_story_letters', 'phase_story_normal', 'phase_story_loading',
  'phase_done',
  'error_signup', 'error_lesson',
];
// Per-letter clip keys — see scripts/generate-voice-clips-elevenlabs.mjs.
// phonics_intro_<glyph>: full sentence "ده حرف جديد. اسمه <name>. ..."
// letter_<glyph>:        standalone letter name "<name>"
const PHONICS_GLYPHS = Array.from(LETTER_GLYPHS);
const RECORDINGS = Object.fromEntries(
  [
    ...STATIC_PHRASE_KEYS,
    ...PHONICS_GLYPHS.map((g) => `phonics_intro_${g}`),
    ...PHONICS_GLYPHS.map((g) => `letter_${g}`),
  ].map((k) => [k, {
    umm_yasmin: `/audio/voice/umm_yasmin/${k}.mp3`,
    amm_hassan: `/audio/voice/amm_hassan/${k}.mp3`,
  }])
);
// Voice samples — only generated in the matching voice (the sample IS that voice).
RECORDINGS.sample_umm_yasmin = { umm_yasmin: '/audio/voice/umm_yasmin/sample_umm_yasmin.mp3' };
RECORDINGS.sample_amm_hassan = { amm_hassan: '/audio/voice/amm_hassan/sample_amm_hassan.mp3' };

// Per-guide ElevenLabs letter-name recordings replace the Antura MSA WAVs.
// When speak() is handed a bare glyph, it derives the key letter_<glyph>
// and looks up the recording in RECORDINGS for the active guide.
const LETTER_GLYPHS = new Set([
  'ا','ب','ت','ث','ج','ح','خ','د','ذ','ر',
  'ز','س','ش','ص','ض','ط','ظ','ع','غ','ف',
  'ق','ك','ل','م','ن','ه','و','ي','ة','ء',
]);

let _audioUnlocked = false;
// Track the in-flight HTMLAudioElement so a new speak() can stop it before
// starting fresh. Without this, an auto-fired phase prompt would race with a
// ListenButton tap and play both clips on top of each other.
let _currentAudio = null;
// Single-slot queue: next thing to play when the current clip ends naturally.
// Auto-advance on phase change pushes here so users hear the previous prompt
// finish instead of getting cut off mid-sentence. User taps clear it.
let _queued = null;

function clearQueue() { _queued = null; }

function flushQueue() {
  if (!_queued) return;
  const { input, opts } = _queued;
  _queued = null;
  speak(input, opts);
}

function stopAll() {
  clearQueue();
  if (typeof window !== 'undefined' && window.speechSynthesis) {
    window.speechSynthesis.cancel();
  }
  if (_currentAudio) {
    try {
      _currentAudio.pause();
      _currentAudio.currentTime = 0;
    } catch { /* noop */ }
    _currentAudio = null;
  }
}

function isAudioActive() {
  if (_currentAudio && !_currentAudio.paused && !_currentAudio.ended) return true;
  if (typeof window !== 'undefined' && window.speechSynthesis?.speaking) return true;
  return false;
}

function loadVoicesOnce() {
  if (typeof window === 'undefined' || !window.speechSynthesis) return;
  // Touch getVoices so Chrome starts loading; the voiceschanged event will
  // populate them. We don't need to cache — pickVoice reads fresh each call.
  window.speechSynthesis.getVoices();
}
loadVoicesOnce();

function pickVoice(gender) {
  if (typeof window === 'undefined' || !window.speechSynthesis) return null;
  const voices = window.speechSynthesis.getVoices();
  if (!voices.length) return null;

  const arabic = voices.filter((v) => /^ar(-|_|$)/i.test(v.lang) || /arabic/i.test(v.name));
  if (!arabic.length) return null;

  const egyptian = arabic.filter((v) => /ar-eg/i.test(v.lang) || /egypt/i.test(v.name));
  const pool = egyptian.length ? egyptian : arabic;

  const wantFemale = /female|woman|amira|hala|laila|layla|maryam|sara|salma|noura|hoda|yara/i;
  const wantMale = /male|man|hamed|hassan|tariq|nasser|omar|karim|shakir/i;
  const want = gender === 'female' ? wantFemale : wantMale;

  return pool.find((v) => want.test(v.name)) || pool[0];
}

/**
 * Call from any user gesture (e.g. the first tap) so later auto-speak works.
 * Browsers require a gesture before audio can play.
 */
export function unlockAudio() {
  if (_audioUnlocked || typeof window === 'undefined' || !window.speechSynthesis) return;
  try {
    const u = new SpeechSynthesisUtterance('');
    u.volume = 0;
    window.speechSynthesis.speak(u);
    _audioUnlocked = true;
  } catch { /* noop */ }
}

/**
 * Speak a line. Accepts a string, or { key, text } so recordings can override.
 *   speak('مرحبا', { guide })
 *   speak({ key: 'welcome', text: 'مرحبا' }, { guide })
 */
function speakViaTTS(text, guide, rateOverride) {
  if (!window.speechSynthesis || !text) return;
  stopAll();
  const shape = GUIDE_SHAPE[guide] || GUIDE_SHAPE.umm_yasmin;
  const utter = new SpeechSynthesisUtterance(text);
  utter.lang = 'ar-EG';
  utter.rate = rateOverride ?? shape.rate;
  utter.pitch = shape.pitch;
  const v = pickVoice(GUIDE_GENDER[guide] || 'female');
  if (v) utter.voice = v;
  window.speechSynthesis.speak(utter);
}

export function speak(input, { guide = 'umm_yasmin', rate, queueAfterCurrent = false } = {}) {
  if (typeof window === 'undefined') return;

  // Queue mode: if something is still playing, save this for when it ends.
  // The latest queued request wins — earlier ones are dropped, so a quick
  // A → B → C transition only fires the C clip after the in-flight one ends.
  if (queueAfterCurrent && isAudioActive()) {
    _queued = { input, opts: { guide, rate } };
    return;
  }

  const key = typeof input === 'object' && input ? input.key : null;
  const text = typeof input === 'object' && input ? input.text : input;

  const clip = key && RECORDINGS[key]?.[guide];
  if (clip) {
    try {
      stopAll();
      const audio = new Audio(clip);
      _currentAudio = audio;
      audio.addEventListener('ended', () => {
        if (_currentAudio === audio) {
          _currentAudio = null;
          flushQueue();
        }
      });
      // Fall back to TTS on play rejection (404, decode error, autoplay block)
      // — but ONLY if we're still the active audio. A subsequent speak() call
      // legitimately aborts us via stopAll() and we must NOT resurrect as TTS.
      audio.play().catch(() => {
        if (_currentAudio === audio) speakViaTTS(text, guide, rate);
      });
      return;
    } catch { /* fall through to TTS */ }
  }

  // Single-glyph input → look up the per-guide ElevenLabs letter-name clip.
  if (typeof text === 'string' && LETTER_GLYPHS.has(text)) {
    const letterClip = RECORDINGS[`letter_${text}`]?.[guide];
    if (letterClip) {
      try {
        stopAll();
        const audio = new Audio(letterClip);
        _currentAudio = audio;
        audio.addEventListener('ended', () => {
          if (_currentAudio === audio) {
            _currentAudio = null;
            flushQueue();
          }
        });
        audio.play().catch(() => {
          if (_currentAudio === audio) speakViaTTS(text, guide, rate);
        });
        return;
      } catch { /* fall through to TTS */ }
    }
  }

  speakViaTTS(text, guide, rate);
}

// Exposed for ListenButton or anything that wants the shape rendered uniformly.
export { GUIDE_SHAPE };

export function stopSpeaking() {
  stopAll();
}
